replicaCount: 1

image:
  repository: email-service
  tag: local
  pullPolicy: Never

serviceAccount:
  create: true
  name: email-service
  automount: true
  annotations: {}

service:
  type: ClusterIP
  port: 3004
  targetPort: 3004

containerPort: 3004

env:
  NODE_ENV: development
  PORT: "3004"

  KAFKA_BROKER: "kafka:9092"
  KAFKA_CLIENT_ID: "email-service"
  ENABLE_KAFKA: "true"

  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 30
  periodSeconds: 20

readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
