apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: ecommerce-dev
  labels:
    app: order-service
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.service.targetPort | quote }}

  KAFKA_BROKER: {{ .Values.config.kafkaBroker | quote }}
  KAFKA_CLIENT_ID: {{ .Values.config.kafkaClientId | quote }}
  ENABLE_KAFKA: {{ .Values.config.enableKafka | quote }}

  REDIS_HOST: {{ .Values.config.redisHost | quote }}
  REDIS_PORT: {{ .Values.config.redisPort | quote }}

  JWT_EXPIRES_IN: {{ .Values.config.jwtExpiresIn | quote }}
