replicaCount: 1

image:
  repository: order-service
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3006
  targetPort: 3006

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  nodeEnv: development

  kafkaBroker: kafka:9092
  kafkaClientId: order-service
  enableKafka: "true"

  redisHost: redis
  redisPort: "6379"

  jwtExpiresIn: "7d"
