{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: payment-service-secret
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: ecommerce
  path: payment-service
  destination:
    name: payment-service-secret
    create: true
  refreshAfter: 30s
  vaultAuthRef: payment-service-auth
{{- end }}
