apiVersion: v1
kind: ConfigMap
metadata:
  name: email-service-config
  namespace: ecommerce-dev
  labels:
    {{- include "email-service.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: {{ .Values.env.PORT | quote }}

  KAFKA_BROKER: {{ .Values.env.KAFKA_BROKER | quote }}
  KAFKA_CLIENT_ID: {{ .Values.env.KAFKA_CLIENT_ID | quote }}
  ENABLE_KAFKA: {{ .Values.env.ENABLE_KAFKA | quote }}

  SMTP_HOST: {{ .Values.env.SMTP_HOST | quote }}
  SMTP_PORT: {{ .Values.env.SMTP_PORT | quote }}
