apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: email-service-secret
  namespace: ecommerce-dev
spec:
  type: kv-v2
  mount: ecommerce
  path: email-service

  vaultAuthRef: email-service

  hmacSecretData: true
  refreshAfter: 1m

  destination:
    name: email-service-secret
    create: true
