apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: notification-service-secret
  namespace: ecommerce-dev

spec:
  type: kv-v2

  mount: ecommerce

  path: notification-service

  vaultAuthRef: notification-service

  hmacSecretData: true

  refreshAfter: 1m

  destination:
    name: notification-service-secret
    create: true
