apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cart-service-secret
  namespace: ecommerce-dev
spec:
  type: kv-v2
  mount: ecommerce
  path: cart-service
  vaultAuthRef: cart-service
  hmacSecretData: true
  refreshAfter: 1m
  destination:
    name: cart-service-secret
    create: true
