{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "invoice-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "invoice-service.name" . }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
