{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: invoice-service-secret
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2

  mount: ecommerce

  path: {{ .Values.vault.secretPath }}

  destination:
    name: {{ .Values.vault.secretName }}
    create: true

  refreshAfter: 30s

  vaultAuthRef: invoice-service-auth
{{- end }}
