apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: analytics-service-secret
  namespace: ecommerce-dev
spec:
  type: kv-v2
  mount: ecommerce
  path: analytics-service

  vaultAuthRef: analytics-service

  hmacSecretData: true

  refreshAfter: 1m

  destination:
    name: analytics-service-secret
    create: true
