apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: ecommerce-dev
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: console
      port: 9001
      targetPort: 9001
