apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: ecommerce-dev
  labels:
    app: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: {{ .Values.zookeeper.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: client
              containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "{{ .Values.zookeeper.port }}"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 20
            periodSeconds: 10
