apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: shipping-service
  namespace: ecommerce-dev
spec:
  method: kubernetes
  mount: kubernetes
  vaultConnectionRef: vault-connection

  kubernetes:
    role: shipping-service
    serviceAccount: shipping-service
