replicaCount: 1

image:
  repository: product-service
  tag: dev
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: product-service
  automount: true
  annotations: {}

service:
  type: ClusterIP
  port: 3003
  targetPort: 3003

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  nodeEnv: development
  kafkaBroker: kafka:9092
  kafkaClientId: product-service
  enableKafka: "true"
  redisHost: redis
  redisPort: "6379"
  jwtExpiresIn: "7d"
