apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: product-service-secret
  namespace: ecommerce-dev
spec:
  type: kv-v2
  mount: ecommerce
  path: product-service

  vaultAuthRef: product-service

  hmacSecretData: true

  refreshAfter: 1m

  destination:
    name: product-service-secret
    create: true
