apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce-dev
  labels:
    app: user-service

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      enableServiceLinks: false

      serviceAccountName: {{ include "user-service.serviceAccountName" . }}

      containers:
        - name: user-service

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: user-service-config

            - secretRef:
                name: user-service-secret

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
