{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "refund-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: refund-service
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
