apiVersion: v1
kind: Service
metadata:
  name: refund-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: refund-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: refund-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
