apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "admin-service.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "admin-service.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
