{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: admin-service-secret
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2

  mount: ecommerce

  path: admin-service

  destination:
    name: admin-service-secret
    create: true

  refreshAfter: 30s

  vaultAuthRef: admin-service-auth
{{- end }}
