{{- if .Values.vault.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: admin-service-auth
  namespace: {{ .Release.Namespace }}
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: {{ .Values.vault.role }}
    serviceAccount: {{ include "admin-service.serviceAccountName" . }}
    audiences:
      - vault
{{- end }}
